services:
  backend:
    image: ghcr.io/kit-tva/cfmtoolbox-webeditor-backend:main
    name: cfmtoolbox-webeditor-backend
    ports:
      - "3001:8000"
  frontend:
    image: ghcr.io/kit-tva/cfmtoolbox-webeditor-frontend:main
    name: cfmtoolbox-webeditor-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    